[workspace]
members = [
    "cynic",
    "cynic-codegen",
    "cynic-proc-macros",
    "examples",
    "cynic-querygen",
    "cynic-parser",
    "cynic-querygen-web",
    "tests/querygen-compile-run",
    "tests/ui-tests",
    "xtask"
]

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1

# Temp
debug = true