name: Deploy cynic-querygen-web

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - name: Install cargo-make
      run: curl -o cargo-make.zip -L https://github.com/sagiegurari/cargo-make/releases/download/0.31.0/cargo-make-v0.31.0-x86_64-unknown-linux-musl.zip && unzip cargo-make.zip && mkdir -p ~/.cargo/bin && cp cargo-make-v0.31.0-x86_64-unknown-linux-musl/cargo-make ~/.cargo/bin
    - name: Build cynic-querygen-web
      run: cargo make build_release
      working-directory: ./cynic-querygen-web

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install JS deps
      run: npm install
      working-directory: ./cynic-querygen-web/js
    - name: Build JS
      run: npm run build
      working-directory: ./cynic-querygen-web/js
    - name: Construct release
      run: mkdir release && cp index.html release && cp -r pkg release && cp js/dist/index.js release/pkg/gql.js
      working-directory: ./cynic-querygen-web
    - name: Deploy cynic-querygen-web
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=cynic-querygen-web/release
      env:
        NETLIFY_SITE_ID: ${{ secrets.QUERYGEN_NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.QUERYGEN_NETLIFY_AUTH_TOKEN }}
