name: Build & Test Rust

on:
  push:
    branches: [master, staging, trying]
  pull_request:
    branches: [master]

env:
  CARGO_INCREMENTAL: 0
  # TODO: Would be nice to disable warnings here too, but there are too many of them.
  RUSTFLAGS: "-W rust-2021-compatibility"
  RUST_BACKTRACE: short
  CI: 1

jobs:
  build-rust:
    runs-on: ubuntu-latest

    steps:
      - uses: kvrhdn/gha-buildevents@v1
        with:
          apikey: ${{ secrets.BUILDEVENTS_APIKEY }}
          dataset: github-action-buildevents

          # The job status, this will be used in the post section and sent
          # as status of the trace. Must always be ${{ job.status }}.
          job-status: ${{ job.status }}

          # Optional: this should only be used in combination with matrix builds. Set
          # this to a value uniquely describing each matrix configuration.
          # matrix-key: ${{ matrix.value }}

      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Build cynic
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace

      - name: Build tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --no-run --all-features

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --all-features

      - name: Build example tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --no-run --examples

      - name: Run example tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --examples
